version: '3.9'

services:

  mongodb:
    image: mongo:latest
    restart: always
    env_file:
      .env
    volumes:
      - ./backend/data-db:/data/db
    ports:
      - "${MONGO_INITDB_PORT}:${MONGO_INITDB_PORT}"

  django:
    image: django
    build: ./backend
    restart: always
    env_file:
      .env
    volumes:
      - ./backend:/django
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    depends_on:
      - mongodb

  vuejs:
    image: vuejs
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "${VUEJS_PORT}:${VUEJS_PORT}"
    volumes:
      - ./frontend:/vuejs
      - /vuejs/node_modules
    depends_on:
      - django

volumes:
  postgres_data: